### ISSUE TITLE
validHex Expression to Complex

### ISSUE THREAD

**Issue by svh1985** [adafruit/Adafruit_BluefruitLE_OSX#1]
Hi,

I've compiled the code but got an error on the validHex filter:

> /Adafruit_BluefruitLE_OSX-master/Bluefruit Buddy/Utilities & Extensions.swift:127:50: Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

`let validHex = self.lowercaseString.characters.filter() {                                                  // Strip out any non-hex characters
            return ($0 >= "a" && $0 <= "f") || ($0 >= "0" && $0 <= "9")
        }`

Cheerse!

**Comment by kevykk** [comment]
Hi svh. We've updated the project to work with the upcoming Swift 3.0 and resolved this error as well. Swift is still a work in progress so it can sometimes report unusual ghost errors like this one.
Thanks,
Kevin

**Comment by svh1985** [comment]
It works like a charm 👍 

Thanks for your quick response!

**Comment by kevykk** [comment]
UR most welcome! Enjoy.
